name: Continuous Integration
on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
        
      - name: Install Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Check Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check Build
        uses: actions-rs/cargo@v1
        with:
          command: check

  test-windows:
    name: Windows Tests
    needs: check
    runs-on: windows-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --no-run
        env:
          CARGO_INCREMENTAL: 0

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
        env:
          CARGO_INCREMENTAL: 0

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --no-run
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"

      - name: Gather Coverage Data
        id: coverage
        uses: jcdickinson/action-grcov@v0.1.8
        with:
          coveralls-token: ${{ secrets.COVERALLS_TOKEN }}

      - name: Upload Coverage Data
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ${{ steps.coverage.outputs.report }}

  test_finalize:
    name: Test Teardown
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Coveralls Finalization
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
